---
title: "Estoques"
subtitle: "Controle de Estoques Utilizando Cadeias de Markov"
author:
  - Salvador Alves Ferreira Netto (2022040141)
  - Nicolas Monteiro ()
  - Gustavo Aledi ()
abstract: ""
lang: pt
format: 
  pdf:
    toc: true
    fig-pos: "H"
    #toc-title: "Summary"
    toc-depth: 3
    #toc-location: right
    number-sections: true
    number-depth: 3
    documentclass: report
    fig-cap-location: top
    geometry:
      - top=3cm
      - left=3cm
      - right=2cm
      - bottom=2cm
execute:
  echo: false
  warning: false
  output: false
---

```{r}
library(tidyverse)
library(markovchain)
library(igraph)
```

# Introdução

A gestão eficiente de estoque é um componente vital para o funcionamento bem-sucedido de qualquer negócio que lida com produtos tangíveis. A otimização dos níveis de estoque é crucial para garantir a disponibilidade de produtos para os clientes, ao mesmo tempo em que minimiza os custos de armazenamento e reposição.

Neste contexto, os modelos de Cadeias de Markov têm sido amplamente aplicados na previsão e gestão de estoques, oferecendo uma abordagem analítica poderosa para entender as mudanças no nível de estoque ao longo do tempo. Esses modelos, baseados na teoria das probabilidades e processos estocásticos, permitem prever o comportamento futuro do estoque, considerando as transições probabilísticas entre diferentes estados.

O **método s e S**, dentro do contexto das Cadeias de Markov, é uma estratégia popular para determinar os pontos de reabastecimento ideal. Ele consiste em estabelecer dois pontos de controle: o nível mínimo no estoque (s) e o nível máximo de estoque (S). Quando o estoque atinge o nível mínimo ou abaixo dele, uma nova encomenda é feita para reabastecer o estoque até o nível máximo estabelecido.

O principal objetivo deste trabalho é explorar e aplicar o modelo de Cadeias de Markov em conjunto com o método s e S para a gestão de estoque. Este estudo buscará analisar como esses modelos podem ser utilizados para otimizar os níveis de estoque, minimizando os custos associados à manutenção de inventário sem comprometer a disponibilidade dos produtos para os clientes.

Serão examinados os conceitos fundamentais das Cadeias de Markov, a aplicação do método s e S na gestão de estoque e como essas ferramentas analíticas podem ser empregadas na tomada de decisões estratégicas relacionadas à reposição de estoque. Além disso, serão discutidos casos práticos e exemplos para ilustrar a aplicação desses modelos em cenários do mundo real.

Por meio dessa pesquisa, busca-se fornecer insights valiosos sobre como os modelos de Cadeias de Markov e o método s e S podem ser implementados para melhorar a eficiência na gestão de estoques, contribuindo assim para o aprimoramento das práticas comerciais e a maximização dos resultados empresariais.

Neste trabalho estamos simulando um caso bem simples de estoque de lojas aplicado. Com isso em mente, vamos supor que estamos pegando dados de uma loja que vende celulares na gutierez, nosso produto em questão é o novo iphone, iphone 13.



